# Flatwhite (light) theme

general {
    col.active_border = rgba(6a4dffee)
    col.inactive_border = rgba(dcd3c6aa)
}

decoration {
    shadow {
        color = rgba(93836c66)
    }
}

misc {
    background_color = rgb(f7f3ee)
}
