# Gruvbox (dark) theme

general {
    col.active_border = rgba(458588ee)
    col.inactive_border = rgba(504945aa)
}

decoration {
    shadow {
        color = rgba(1d2021ee)
    }
}

misc {
    background_color = rgb(282828)
}
