font_family CaskaydiaCove Nerd Font Mono
font_size 16
disable_ligatures never

include current-theme.conf

allow_remote_control yes
listen_on unix:$XDG_RUNTIME_DIR/kitty-{kitty_pid}

scrollback_lines 10000
cursor_shape block
cursor_blink_interval 0
confirm_os_window_close 0

window_padding_width 8
