font_family CaskaydiaCove Nerd Font Mono
font_size 16
disable_ligatures never

include current-theme.conf

allow_remote_control yes
listen_on unix:$XDG_RUNTIME_DIR/kitty-{kitty_pid}

scrollback_lines 10000
cursor_shape block
cursor_blink_interval 0
confirm_os_window_close 0

window_padding_width 8

# Russian layout duplicates for default hotkeys
map ctrl+shift+с copy_to_clipboard
map ctrl+shift+м paste_from_clipboard
map ctrl+shift+ы paste_from_selection
map ctrl+shift+щ pass_selection_to_program
map ctrl+shift+т new_os_window
map ctrl+shift+ц close_os_window
map ctrl+shift+е new_tab
map ctrl+shift+й close_tab
map ctrl+shift+д next_layout
map ctrl+shift+у open_url_with_hints
map ctrl+shift+р show_scrollback
map ctrl+shift+п show_last_command_output
map ctrl+shift+я toggle_fullscreen
map ctrl+shift+а move_window_forward
map ctrl+shift+и move_window_backward
map ctrl+shift+к start_resizing_window
map ctrl+shift+з>а move_window_to_top
map ctrl+shift+з>т kitten unicode_input
map ctrl+shift+ф>д set_tab_title
map ctrl+shift+ф>ь toggle_maximized
